### PR TITLE
Angular WordPress Shortcodes

### PR DESCRIPTION
**Pull request by arniebradfo**
I've created a system by which WordPress shortcodes can be rendered as Angular components when a page's content is loaded.

for example,
```
[app-shortcode class="these are some classes" input="value" ]
	<p>this content is inside the <code>app-shortcode</code> component</p>
[/app-shortcode]
```
in the content of a post will trigger the Angular JIT compiler to render a template that looks like
```
<app-shortcode class="these are some classes" input="value" >
	<p>this content is inside the <code>app-shortcode</code> component</p>
</app-shortcode>
```
with the `input` attribute passing `value` to the Angular component instance.

Now WP page and post content can leverage Angular components.

Thanks for writing that tutorial. Maybe you should add this to the tutorial set.

-James

### CODE REVIEW

**Comment by stuartkuentzel** [comment]
This is fantastic work, thanks! Only issue I'm running into is building for prod. This seems to be working for me on `ng serve` and `ng build`, but `ng build --prod` throws an error "Runtime compiler is not loaded". Any ideas on this?

**Comment by arniebradfo** [comment]
Probably the JIT compiler is not being added when it optimizes for production. Ill look into it.

**Comment by arniebradfo** [comment]
OK so

The problem is bigger than that. It seems that while running in development mode, Angular always uses its JIT Compiler to quickly reload edited portions of the code. When the code is compiled for production, Angular uses the AOT Compiler which makes a much smaller package size and faster running code. The AOT Compiler, however, will not allow for dynamic templates.

**So there's 3 options:**
1. Just use the JIT Complier in production code. `ng prod --prod --no-aot`
    - slower running code
    - larger file sizes
    - dynamic content
    - for small projects, its ok
2. Use some hacky combination of JIT+AOT like [this](http://junny-jasmineorange.blogspot.com/2017/02/angular2-how-to-load-forms-dynamically.html)
    - best of both worlds
    - hacky
    - might not actually work, seems like it might only work in Angular 2.x
    - more references to this approach
      - [here](https://github.com/angular/angular/issues/12885#issuecomment-260836756)
      - [and here](https://github.com/angular/angular-cli/issues/5275)
3. Wait till the Angular team adds their version of dynamic component creation, and do it their way.
    - would probably work great
    - this may never happen

**Comment by arniebradfo** [comment]
I've confirmed the `ng build --prod --deploy-url="/wp-content/themes/{THEME_DIRECTORY_NAME}/dist/" --no-aot` works.

wpautop should also be disabled `functions.php` with this:
```
remove_filter( 'the_content', 'wpautop' );
remove_filter( 'the_excerpt', 'wpautop' );
```
or WP will put random `<p>` tags everywhere and prevent the template from parsing.

**Comment by arniebradfo** [comment]
Hey, Its been a while.

I figured out a way to make this (and a bunch of other stuff) work in the Angular frontend. I basically made an angular WP boilerplate theme. 

Its still missing a couple of things. Maybe you want to help out?

You can check it out [here](https://github.com/arniebradfo/ng-wp-theme). It is a fork of this repository.

As for the shortcodes, I finally found a good way to make it work with AOT. They're called "Embeddable" Components. Its the same system used by the angular.io documentation site. Here's a [video](https://www.youtube.com/watch?v=__H65AsA_bE&feature=youtu.be&t=2h14m13s) about it and an [example repository](https://github.com/wardbell/ng-dynamic-app).

This PR is a dead end so I'm closing it.

Thanks!

**Comment by stuartwk** [comment]
@arniebradfo Hey, the fork looks amazing man! I'd love to contribute, but I'm crazy busy at the moment. I gotta dig into your code more, the functionality you added looks awesome. Also, thanks for the cred.

**Pull request closed without merging**
